import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Subscribe } from "../components/Subscribe";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Everything Good</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto h-screen max-w-4xl border-l border-r border-r-gray-200 px-4">
        <h1 className="pt-5 text-center font-eb text-7xl font-medium md:text-8xl">
          Everything Good
        </h1>
        <p className="mt-4 text-center font-robo text-2xl font-bold">
          Guides to everything good in the city
        </p>
        <div className="p-3" />
        <p className="text-center font-inter">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit laborum
          commodi architecto labore aliquam, dolorem quaerat ab a exercitationem
          eaque odio. A rem magni inventore error quia aut sunt itaque! Lorem
          ipsum dolor sit amet consectetur adipisicing elit. Aperiam repudiandae
          incidunt minima similique alias possimus corporis earum dolor laborum,
          quo eligendi, rem maiores eveniet. A, ipsa! Nostrum fugit repudiandae
          sequi?
        </p>
        <div className="p-3" />
        <div className="m-2 flex flex-col rounded border bg-gray-200 py-3 px-3 shadow-lg">
          <h2 className="stracking-wider pb-2 font-inter text-2xl text-gray-800">
            Guides:
          </h2>
          <Link className="font-robo font-bold hover:text-red-600" href="/les">
            - on the Lower East Side
          </Link>
          <Link
            className="font-robo font-bold hover:text-red-600"
            href="/soho-noho"
          >
            - in Soho and Noho
          </Link>
          <Link
            className="font-robo font-bold hover:text-red-600"
            href="/nolita-chinatown-littleitaly"
          >
            - in Nolita, Chinatown, and Little Italy
          </Link>
        </div>
        <div className="p-3" />
        <Subscribe />
      </div>
    </>
  );
};

export default Home;
